
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;
pragma AbiHeader pubkey;

// This is class that describes you smart contract.
contract TonTokenWallet {
    
    uint256 public tokens;

    function getBalance() public (uint256 balance) (get-method)

}
